In [18]:
%reload_ext autoreload
%autoreload 2

In [46]:
import pandas as pd
from pathlib import Path

from mbp.webscraping import activate_web_driver, get_team_page
from mbp.data import download_team_data, get_team_games_for_year
from mbp.paths import SEASONS_DIR, RAW_DATA_DIR

In [144]:
team_name = "Arizona"
raw_year = 2022

In [145]:
driver = activate_web_driver("firefox", True)

# Read team names
df = pd.read_csv(f"{RAW_DATA_DIR}/mbb_team_names_to_number.csv", index_col=0)

In [147]:
from selenium.webdriver.common.by import By

games_df = get_team_games_for_year(driver, df, team_name, raw_year)
games_df.head()

Opp has a # in it: #10 Stanford
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #6 Arizona St.
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #1 UCLA
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #15 Princeton
@Sacramento, CA (2023 NCAA Division I Men's Basketball Championship)

  raw_datetime       opponent    result attendance   datetime  home
0   11/11/2022    Southern U.   W 95-78     13,485 2022-11-11   1.0
1   11/17/2022      Utah Tech  W 104-77     12,752 2022-11-17   1.0
2   11/21/2022     Cincinnati  W 101-93      2,400 2022-11-21   0.0
3   11/22/2022  San Diego St.   W 87-70      2,400 2022-11-22   0.0
4   11/23/2022      Creighton   W 81-79      2,400 2022-11-23   0.0

In [148]:
# Download Arizona data
download_team_data(team_name, raw_year, True)

Downloading Arizona team games
Opp has a # in it: #10 Stanford
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #6 Arizona St.
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #1 UCLA
@Las Vegas, NV (2023 MBB Pac-12 Championship)
Opp has a # in it: #15 Princeton
@Sacramento, CA (2023 NCAA Division I Men's Basketball Championship)
Downloading Arizona team roster
Downloading Arizona team stats

In [149]:
# Get their games for the year
year_dir = Path(SEASONS_DIR / str(raw_year))
team_dir = year_dir / team_name
games_df = pd.read_csv(team_dir / "games.csv")

for opp in games_df['opponent']:
    opponent_games = year_dir / opp / "games.csv"
    if not opponent_games.exists():
        print(opp)
        download_team_data(opp, raw_year)

Princeton
Downloading Princeton team games
Downloading Princeton team roster
Downloading Princeton team stats

In [13]:
# Get games for the year
games_df = pd.read_csv(f"{SEASONS_DIR}/{raw_year}/{team_name}_games.csv")
stats_df = download_raw_team_stats_for_year("Morgan St.", 2022)
stats_df
# for opponent in games_df['opponent']:
    # stats_df = get_team_stats(driver, df, team_name, raw_year)

,Jersey,Player,Yr,Pos,Ht,GP,GS,MP,G,FGM,...,AST,TO,STL,BLK,Fouls,Dbl Dbl,Trpl Dbl,DQ,Tech Fouls,Effective FG Pct.
0,2,"Burke, Isaiah",Sr,G,6-1,31,31,1069:55,31,200,...,86,86,46,9,61,,,,1,8
1,4,"Copeland, Daiquan",Jr,G,6-6,12,7,211:08,12,20,...,23,35,10,1,30,,,1,,2
2,5,"Djonkam, Lewis",Sr,F,6-9,31,29,659:49,31,108,...,35,38,30,15,102,,,9,1,10
3,14,"Fagbenle, Toto",Sr,F,6-9,16,6,214:00,16,16,...,12,14,17,10,35,,,,1,2
4,0,"Hobbs, Kamron",So,G,5-10,31,16,874:11,31,93,...,83,59,44,3,60,,,,2,8
5,31,"Horner, Ty",Sr,F,6-10,26,11,309:01,26,28,...,18,10,10,10,58,,,4,,7
6,3,"Lawson, Rob",Fr,G,6-0,29,1,560:48,29,54,...,51,43,27,1,53,,,1,,8
7,23,"McCullough, David",Sr,G,6-6,19,12,350:40,19,35,...,16,30,18,14,36,,,1,,4
8,11,"Miller, Malik",Sr,G,6-4,19,19,614:25,19,123,...,74,65,39,13,52,10,1,2,,4
9,21,"Nnamene, Collin",Sr,F,6-9,30,3,375:59,30,22,...,14,37,11,42,69,,,2,,9
10,10,"Thomas, Will",Jr,G,6-5,29,8,614:56,29,105,...,37,38,20,7,45,1,,,,6
11,1,"Turner, Khalil",Jr,F,6-8,13,12,314:42,13,47,...,25,22,28,13,41,1,,2,1,2
12,22,"Wiggins, Kevon",Jr,G,6-3,17,0,105:25,17,12,...,5,9,3,,5,,,,,2